version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - doctrine/coding-standard-approvers
  labels:
  - Dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: slevomat/coding-standard
    versions:
    - 6.4.1
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.4
    - 7.0.5
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.5.8
